# Generated by Django 3.2 on 2021-05-07 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0002_auto_20210505_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='medic',
            name='medic_ssn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vaccination.person'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_ssn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vaccination.person'),
        ),
        migrations.CreateModel(
            name='PlaceHasVaccines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.place')),
                ('vaccine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_no', models.IntegerField()),
                ('appointment_date', models.DateField()),
                ('appointment_next_date', models.DateField()),
                ('appointment_priority', models.IntegerField()),
                ('medic_ssn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.medic')),
                ('patient_ssn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.patient')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.place')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccine')),
            ],
        ),
    ]
